create database practise;
select * from practise.customers;
select count(*) from practise.customers;
select count(*) as total_count from practise.customers;
select count(*) as shaktiman from practise.customers;
select * from practise.customers limit 5;
select * from practise.customers limit 5 offset 23;
select * from practise.customers limit 2 offset 23;
select max(customerid) from practise.customers;
select min(customerid) from practise.customers;
select * from practise.customers order by CustomerID;
select * from practise.customers order by country;
select * from practise.customers order by city;
select * from practise.customers order by CustomerID desc;
select * from practise.customers order by country desc;
select * from practise.customers order by country asc;
select * from practise.customers order by CustomerID desc limit 1;
select * from practise.customers order by CustomerID desc limit 1 offset 1;
select * from practise.customers order by CustomerID limit 1 offset 1;
select * from practise.customers order by CustomerID desc limit 1 offset 2;
select * from practise.customers order by CustomerID limit 1 offset 10;
select * from practise.customers order by CustomerID limit 1 offset 4;
select * from practise.customers order by CustomerID limit 10 offset 0;
select * from practise.customers order by CustomerID limit 10;
select * from practise.customers order by CustomerID desc limit 10;
select * from practise.customers order by CustomerID desc limit 10 offset 2;
select * from practise.customers order by CustomerID desc limit 8 offset 2;
